//created on: Feb 20, 2017
package rules

import model.Item;


rule "Classify Item - Low Range"
    when
        $i: Item( cost <= 200, category == Category.NA )
    then
        $i.setCategory(Item.Category.LOW_RANGE);
        update($i);
end

rule "Classify Item - Mid Range"
    when
        $i: Item( cost > 200 && cost < 500, category == Category.NA )
    then
        $i.setCategory(Item.Category.MID_RANGE);
        update($i);
end

rule "Classify Item - High Range"
    when
        $i: Item( cost >= 500, category == Category.NA )
    then
        $i.setCategory(Item.Category.HIGH_RANGE);
        update($i);
end
